module.exports = {
  presets: ['module:@react-native/babel-preset', 'nativewind/babel'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        alias: {
          '@screens': './src/screens',
          '@screens/*': './src/screens/*',
          '@navigation': './src/navigation',
          '@navigation/*': './src/navigation/*',
          '@types': './src/types',
          '@types/*': './src/types/*',
          '@components': './src/components',
          '@components/*': './src/components/*',
          '@constants': './src/constants',
          '@constants/*': './src/constants/*',
          '@assets': './src/assets',
          '@assets/*': './src/assets/*',
          '@svg': './src/assets/svg',
          '@svg/*': './src/assets/svg/*',
          '@lib/*': './src/lib/*',
          '@lib': './src/lib',
          '@shared/*': './src/shared/*',
          '@shared': './src/shared',
          '@api/*': './src/shared/api/*',
          '@api': './src/shared/api',
          '@entities': './src/entities',
          '@entities/*': './src/entities/*',
          '@features/*': './src/features/*',
          '@features': './src/features',
        },
      },
    ],
  ],
}
