module.exports = {
  presets: ['module:@react-native/babel-preset', 'nativewind/babel'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        alias: {
          '@screens': './src/screens',
          '@screens/*': './src/screens/*',
          '@navigation': './src/navigation',
          '@navigation/*': './src/navigation/*',
          '@types': './src/types',
          '@types/*': './src/types/*',
          '@components': './src/components',
          '@components/*': './src/components/*',
          '@utils': './src/utils',
          '@utils/*': './src/utils/*',
          '@constants': './src/constants',
          '@constants/*': './src/constants/*',
          '@api': './src/api',
          '@api/*': './src/api/*',
          '@assets': './src/assets',
          '@assets/*': './src/assets/*',
          '@svg': './src/assets/svg',
          '@svg/*': './src/assets/svg/*',
          '@store/*': './src/store/*',
          '@store': './src/store',
          '@lib/*': './src/lib/*',
          '@lib': './src/lib',
        },
      },
    ],
  ],
}
